#!/usr/bin/perl
use warnings;
use strict;
die "program x y density" unless (scalar(@ARGV) == 6);
my ($x, $y, $e, $o, $f, $density) = @ARGV;
# print "$y.ox\n";
print "$y$e$o$f\n";
for (my $i = 0; $i < $y; $i++) {
    for (my $j = 0; $j < $x; $j++) {
        if (int(rand($y) * 2) < $density) {
            print $o;
        } else {
            print $e;
        }
    }
    print "\n";
}
