#!/bin/sh

set -euo pipefail

cd "$(dirname "$0")/.."

if perl script/kernel-doc -none src/* 2>&1 | grep warning > /dev/null ; then
	perl script/kernel-doc -none src/*
	exit -1
fi

# Static analysis with clang-analyzer
scan-build --status-bugs make re > /dev/null

make tests > /dev/null
if [[ $(test/test | wc -l) -gt 0 ]] ; then
	test/test
	exit -1
fi

echo "Everything OK!"
