# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jfrankow <jfrankow@student.42lyon.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 1970/01/01 00:00:00 by jfrankow          #+#    #+#              #
#    Updated: 1970/01/01 00:00:00 by jfrankow         ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

DEPENDENCIES =
LIBNAME      = libft.a
NAME         =

# DEPS_TO_BUILD =
# LDFLAGS =
# LDLIBS =
# CFLAGS =

include common.mk
